const input =`WjmsdnddnmQPZPPJPL
bQllTtpBlgwtrbbCwfZcfSFPSfLCSF
GgVgQrlpphBGrlVGgTtsRHRWVRMzRdVsqdnDnV
MMTcbpnfNGQbMjgsRwSzRptRzz
lPqCCqQdQqQmCPRzRVSwtzgqqwqR
lrDdllPdBWdDFQFnMbDNDn
FldWTldlpBSLzvpnpSTpWbDhbHNDPHhJcNHNDwbH
qVCGQRGrrgMQrJhPNchgvgJhNc
frjGfMrGQMjsRrRQjvQGmrQQszTTpSLBznlzBlLLSBLLSZTn
TPZZZMTTbNTZNtTlTbjPVRVGzpGQLLzdGgmslhzSzgLzQh
wrfwDDvcnFvCfrrSQsmzGGQQdndsGg
qfHwHCqCqCrFJrcBHCCJRmWTRTmVMttjRjRHZMNV
vpbqnzbPmWLFjFLBnjZg
NltQcCClQlcGQGtMTCRdGTGBFZRLZjFFZZhBPLrFHZFjHf
lMtlGMwMsCCNlTwtsCPzzmPmmVpmpWqVWsWz
VmWVSchSrScGtwlVtBnwBVFF
RZZPRNpPCLZvZPZNCLbQPZNBFtttmwBMTMTtttCwtgwBgl
RNNmPvbQQjPRQQNNHpNbhsfzWJqqSJcsGHhHcfhq
dtJvcpccWvLDztRCRRCrCC
qHVslPzPqHqzmPhTzmDFggjrHrSCNFFFSjgR
qPVPMhszZPVhwBZcdpvZJncbcJ
HBNLlBDtvLDHhHLvfwlFjqfQTFqqWfST
ddsGcggJncZVRdGCdZdcWWzSFrjzQFrfTzqfCjFw
VdgscZmbZNBvbDHTbL
GtSZQqpHpHfGHzzqHzHfSbPbnJCrRCnJChmjnJnbSh
DvcTNTDWlNDWdlbnnbjmRhRrCCRd
cclNlwBRvvTNccRlBNRspVLLZzVzVZQqfqqLpzpw
dBSfHdZvMQMdNVpWRmWmLCmmtB
rbTTrrjDcqcrrqrjjJGGclltPCWDmvtpmpPpvRDsCspsLC
vlhjThlqcjrnTvThndddHZngMnfwNQFNFM
tHqfszrgLsvgqtHrHtwVCGBRRjGSCwsCsmmV
MdFMclPmcDQFDlDdlZPmbVpCbFpCbBSCCRGCFpbV
mcDJdDQMcDTZQhhNNPldhhDtvHLgqtzgLvzTzWHWnWfvvz
sVdGlTMMVTGCdsTMHHWWnNBzNWpNWCpW
mPmjFhlwmwmWrpSrSWHB
jhPhjwgthtFFjRwjZgjGdJcdflfqMsZLLsdZdc
CBRsTsBBzLCfLqtqBRPNDQglSttlcgDlgGGt
rJdbrJjrdbVJZdVZCGrNNcgDQlcQrggl
FpFbbppjFCdwmTvsvfzmTnTBfq
cqhcWqqCNjGWqcqhGGZzngftmptLZLGZTn
brJHBbPVHPvSsdHrzQLzZgpfVzpfQtnL
dHFPBPrBJFRzcWNFhWwN
QTBTfQTZsjWDJBJd
FgFWNqWGDPqlPllp
CCvHzSWFrrtvNvNNHLGQQfbVRRfHZcZcVTTTnZ
ZCCHHCVRZzBZQThM
nljDtcqnhcfbwjwltfLQMLLQQppJBMLQJL
qDsqschsqblDqjcqtRmNVVdNsddNNPmFgV
QQRnqGBSpQnMmSGmRQQFtdcbbtHHccjpTFcTfF
wCNPNwNNWNgZHJHJFffqCjbj
ZNPzNWgNrsmzMVqsqs
pVWlMBWjlWWqspWDjdjMpMDCPtmmdbhtQtQtbGPCzChchz
HZNgrHSvHwnFZnvgNvnwLPBGQHmCmtPmtBCGGCmQhG
FrNfvSNSZLZJrJsVlRWWWqRBVTff
PQctSHQDPSQcbShpFzbmFddpmdmR
wqWVwvwNCJRhmdhwJw
nMnWggVqRVZqHBSBsQsQGDSZ
qppwrgZSLsVbbfvZ
hhBHPQQChCDcPcsvvhbGbsllJTfv
MDWmWFCPFWtgpRWjws
bmRjdmrJRjhJdJLZBjTFfHGTtQFTSQBS
wCNVnsspwsnvNDwnsDwSBHtDHHQGTFQFtMrQMS
nWsNvqVgVcqdJrchrz
MZlfqlmblmMRWhWNsjSQfh
CznczgtDFnVtFBNSRNttvhQsNh
SGDFzVrzVPrGHVnzCPVnlZlPwTbpTqlbqLMpbLlq
lbbbGDlwLDLjvDvm
FQfQnLTWVcPChtjmjWSj
cfgzzgfgfVdzTdfNwBpbLbwdRbpZGrdw
mwnWtbmdWdccwtgTmwnQfPqsqLQQJQQLsfQQ
SjrZbhvBZzPHQqfGJfjG
FlrMBSvMZZFBZhShMMdctWDtmFNDbDTmtmpt
ndHWprpqFTnnpdNFlhljzlGTwDGzlhGz
fvZmmVVfJctMZsgMgmcBmsZhwQlGDCzPPZWDGDjCllhC
WsmvmsmRNnpRHdbS
LgZSvhvcsWtcWnjrFrWjjjnPWW
DJDfNlDNRFlpMlFLFP
TmqTqDHdmfwJRwfdQJLHzzSggHZZcGzhtZvcZhzG
lbTpqhhgSlgtlTqSDzzLPPPrLGTTGnLm
VwGfQGBGZWNnmDLPznLB
vQdfZFWvFMMFwWGGhpGqJbpFtgbS
hSvCvFRDwmzCCHrszb
jdMgfTblgjJTLLLzqqGscmPmlqPzHc
bjQLTTbZMfJffZBBWdjBBQwVDntFpRvvDVvSnhppFv
FFnFQndPqzmjHscmJFwc
ZrZrRgDphGGDZgRRBSBNMHHvmwJJSNJHcv
DGrbbthfWWWDgtfffttfpGPVqnmblqPqCdQTlTPCzTll
sHTsGrHpsftmddRRZfRv
MqFcqcMQbMcVPCdFZCzZsRsFzL
qnVlBbcJJbbMcbgQJMMbQlDWWwHWSWwpTsGHGrpDWG
qpmvVVcGvVVcVmDsCfqTHLLJzTjfZzLZ
rSSgwwnSRRBrQrZzZHCQrZ
BFgFRgdNnSBbbnhSMBSNFdsWVtpWmzsGtvpVPvGWVDDN
fBBRfJBzzMRGRzCBgWtbCWtbgHHHWdqt
mvNcDcsDLLnnqfbv
hpTsTsTrDrfpMSFFZjPFMrSP
CNQGGDMFWGnWWvvNMQFPvrgzBLVBLszwgggLgw
mppZVZtZRTbTTpRccVbgrSLzSPSzBrfbPBbSPw
VtZJhRJcTpJTHlhtHZCFFWFjNjGGnFhCqDqG
cppcZGcGgGpdTgSSnmpFMFrFzmwqwmrHwz
RStQJNCNvfBQNjrqmrjFrBMzFB
LJDNNJCDLcdLnSVd
gNrBNSrNNtSjBndzmzlVnm
MbfqfpCLpCsLqsLFSbQLfnMdcdRRcdzldlnljzncnJ
QPQLqZqhSqhvtvTTWrNg
DtrrcGvtLnrrvLrfctfHztrfQpbwwphpdSbbPPPwFSFFRPwH
gggBqTNdTNjqWBlNmCqCmNggQPhpPPPbhhQpSBpJwbSJSQFR
ZglTmgWNgVZMZdsGMcvDcMdMnz
bjtTFsPmmtpvVlQHlQJQnJjn
WzDzwLCSLrrDNLdrSZRCwNzrlQlJMnJQJJVhbcMhgllwnJQh
fRCZzrWRzzGbGvTmBPTf
lVlfJVblPQbllflfLdJdvGpjnFRFqJFnDqpJjnpF
HcwZMgmwWCHHCSwcWCcgSCtCqqpFppGDqvDnRhgnnqFDpjFT
cwCHtGrCssWHCCWZZMbPPNBVbNfVbPllVszf
DSpSnRwrZDPWsJdZ
zjjlQVjlNZmCVCfhCfgFFfFFFqWJbgbFWHJH
lNQMlGjQBZjCmhNMCChGzlVNrpTnccLLwcRwTSppSpprLRcB
vLfvcgglbfLfgqdgNpPtzqDmPzmJTTztPCHT
ZWSQVGwQcWjSshGwVcnSzDJZtPPTzmzzJHCTzDtJ
SjVSrWVhQVQhwrLMcrFbfplcflvv
NgtfSRPnnRrSlgsPhnShDWQlMWpVBMMMpCWVBpCQBB
LLJnvwJvZHZbHTbVCQBppCFJCWWQBz
wHTGZmZvdvLvjLwZdqngNgsGtrDPSDhtNfDf
DwrDRlrwmbSbRgwsSbRwGJvQGqjJqGNTJTNGTSGn
PZdMZzCQFBZWWFQvJZvcNcjqNjjZJG
WHWCFHBBdzzMWhPFtFdMzlRsVbVmDrRVVrtQplwVwD
bpWbJMWpJbprfNMrBfJfprWhPnGtnHnLHjPPjLvsWnHGvGvj
qZdgVVgDQhQZlwcqgDcchldjjmLtntmntPQsmLnLPjssnL
RVRlgcSSdglZczdqbTCrhBrBpNBSBSbF
SgbGvfbnGgmnNnnzqMqqHHRzbZBzZR
TWlssdFwWdtswWPtTtWltwdVHlZZzRHZBZRzrprqHMpqgZrq
dssdCWTFwSvgmDjDCG
pqsDnNzzZsdZSnDSpwjBCBWvgjvWjNFWQgWC
lVGtRtLMGGfbTGTtTbQCQnBQBnBFgFQcgjfc
GPbTbPtnPttmLTGRRbtmdwSDwpwwhZqmdpzDhDJd
MdccRQMJvHdgZggvhjjMgHcHlWWqFFWmGqFbJWzzFLWlLmPm
TDpSsTrtblSzQlGQ
tfVNrwTwtswTssMRjMMQQddNMRCd
GqGqGpFqqgDGFRqDwwqqmzpGTLPvVWMPVCPLJLRJJMLTlCWV
rHrSbrsbQcbtdNHHHfdPlvWBLLWlvMTVlVLCJf
rccbtthHSHsNHrrcttwqpnDFnMmpnzFnFhnF
vQQQbRvlLjNNLLBzNllNHNBqGqhMWhGGhTqmPmqhWTFhRm
tnsZwgSnCDrZSCDsfTMSGpPWmPSWmGmbFq
CrVnfnCCtrCgfrffcrstDnJNlvJdNvzdBcHdLBJHvbBv
nmQsMqTnLlmmpQZmTZcdHwCFSpHJSSWHSJVSWSHH
vRgRRtfPvDjzDgDbsjzRvjfNNWWCSJFwrHCFbrCJWJHCSC
GhsRBztDBgzRPstgzBLZcqmlcLMMlmdLQBZT
CWfvvhfWrlllSSRrdQrQDQGQdTRr
jsNctMZLmMZLMmmmbbNZswZNqBTHPHzBMHHTMGqBRMRPDQqP
jcwjntLngngplgFhgRvJVp
vchzqzwlhzRqzVZQwqtVPZLnLLbDnDFnbGLnDbPLDGWD
pBTHpdpHsrNBBsgdrdCpCpCgRFCMFDLFWWnFWLRRGWbDFGSF
prsBHfggjpjjcRQlqvtw
VDwzLQrDDWrrwWbJrVJwVrVQfMfSCNPMfSlMlPcMmThChf
tsjFdsRsgtRmGZHpHRgBClSlGSClcPhGCfPlllll
qBBFBZZpmgdFHdstjFJbzVwJVqJWWbrvWJDL
mgjZmrqmdsmGtDplglJgRVVc
nPhnLvnHLtLnWzzcNwwcchVJRflhpc
SnnLntLWZsMqZrSZ
jcrNfnrNLNNqFgbDfCSgSQbS
zPPHtMrGGptvTWPVvzvHRgQsbDsSRRCCQbtJsJDS
wHzrWVzPwThGGwMHzTGGPGwhdlZnBndZLljNjBcLdZdNBN
qNPhNqddBNhqvPhFvllNgNBHCrrCQnjpCfPVJnnJQJCjJj
ZZbZTZcmGWWMDWRSDnBVQCjVDffJjnnVCJ
SGBRTTZGGcLSSWTScsmcMbGlhgwFqslhzqggghwhNvwwvw
GCCPwpsBqNSsBPpSCrSshzQzLhTvQhqTnhtTVQcT
JDjFJfMJgWbWWlDJcnvvhvtdLnjnzhjz
FlDflbZfZgJgMgbmgZJfSpGCvvrGrRCpCBrZRprw
HwqhgFGSMgPPCGQQQnvvcpjn
BllbdfRBsBmsmZlBTmQCjTnNWNCmNmvc
lJDlBflDdbbRlLbfsbZBJtbRqrVFPnwwwhVMHwVrgJwwrSwH
LTvLtTFLCddFTTthsbVVmHHcqVHmWRcmHL
lBgwwNggwMwNVbjBCQcCqCRB
nCMCwZGGNGJnGhtrzsdDDndtsF
ZlZdJJplLZBDpJjNJlGjQCLmCQmTwVVCbQQbqWCT
SfgFzftrnRzMnVbPPPQmPq
FfmrRvgShchvFfghzRvgtvFBpJDpcGNGdBHJlpDDDJlDJZ
LdNrLzjdWQnrDHsD
tBZmBZtVZpldVMPRnsRQsnnsHVbRHs
MlfldwMBBFMZTSFTSqLqcvSJ
nJqBlvvBjHhBcqqRrGPrTrGpBCGzTG
MfVCVMLZVZtQCdtLMtQtQSSSTSzFRSRPFpFRGpdTFd
CCQQtQVgfbbQNggsNfQZZbHbcWmnhlhnvlnlHjJWvnhv
SGmmGwVwnmhbhnhwhhwbdMgNNgjmvMDrJTCgmBTBBj
ztFWcWQQfcRzzRFllvjDjggjDDfBgJMBgC
QtzcJtFtqcFQRRWRRQWFzFGpVnVSGLLGZVGVqddbLqGL
tBmdmQtjMMqDLqBtttQMjDdwwgwccMMbffllgzncwfFflF
TPVHTVsRsJVHVrVvHvrRhVJbfCgFbzwbCGgFlwgcCwbn
hssVWnRrTVZSSZZqjLddWtLBddqtQL
WhhtGZtZGQZmvCfCwtvhqgbfdDJdfjlSDlSlBBJDSg
rHnpFHnDrdBggJngnL
HVcTzFPNzTpPPVrzmtwtvvvmNQwDQvWw
dStBwStGGBrNnBdrSSMzvjhgFcvvDcnnvPDn
RLZbCWWJbHRsTHspZWLcDWcPPhzczfjgPjjvjz
ZmLHJqJsLJJHLRsmmmGSztQdQzmNBrBN
JrmRVdvcmvvmvvRTdBVVfjFQLwjqLFLWFMqwcFjz
DDhhttDHHHbHSnsDbHqMqzwQLLFwLsjjLLQf
bSbPthtgGQPNPHnSDChCRJZZJRCZdCrCBZZZZvJd
rqvVqNJpVVNwnqqTwthMMq
jsFRFDQRLQDQmsPRmQsmcQFMzGhwBGBhTzTTzHnRhnhBhRwz
dCccQcQsFCmCQfbJbvZMNZfJrJll
TGjrrTRLHvrQrFDCrmzzVm
NwWqqhndWtzDQhCzVCsh
CSSwNNwqgBBBBbGGvLTTvb
fRBRBHCVRRzcCdZHvRvZVCZLNjtwtNwNTtLjNtTpTNttfS
DZshMssZmTMjwjSLtw
QPrJDDJsPDFmFrFDscHHRzrcvccCZRVzrR
zgqzLLvlvdgpgrWpWW
RnJmNRncnScFmZSScrJQQdbpGdHbWHtPHpBHsdFdsW
JDfRcrSnmDSJcNfrNZNjvlwjhllhMzlDqMqMvh
fDLzSMLhhtDWMvtjCRRZjCHHJjChHN
pmTNpVwPNbPwPBFRqRJqjCnFjZFV
dTwpddsTbgbQBssprsgtvgcNLzWMctfSgcfWLt
fbBsBTsNDhGBGZcLLLJJQffQLQ
MpsCCMHClsHQqZcQWLqR
FtjdCFzVljFlslVCpFrFjPhggBGDgNSTTgbGNmbGTr
HqTfmsCFmPlGHddNVGpLhz
JjjcQQJgjZvZZzzwgpNVGwLGgV
nQnSbDDRbSQJQQpRZtZcZZsPPrFfWCPFWlrFsFPqmqFt
TgTDDrCmqJDGLrhqLmLGqDQRFtttjMbQZJjtdtjFdsdF
WHffcHWnlvvcSSWzPVvHpWWVRbFdQQtQnjwZFMwZtwddsZbd
cBpPplVVPfvVGBDLGCBqmmLM
dlMMmnmjvCCjJrrvMdgHcbcFbqFbzQrFbGzb
tPhRBRZPtZRshTzRsNShRZNGDfGgFFbFQqbGHDHbqfGD
TSPhBVsTwRBTpVtRZpVhZLJjWzLjJlJlJvmwWWzwWn
WcvLLgLcczLTDtccbLcgzMMfPsGwRPjwfMwHMfMvMp
QVmlPQCdJlJJJlFJJJnPQQhlwwMMMnMwNMpwMGwwfswwGMsR
lrSCZZVFhPSZgzgWttWBcc
bwbbZLlbwlJhBzFCgtTGRGQldQRmQW
SSnpHnPHqpmggCWgdT
PPscHHTfcsPSDVfVssjvwFJLBJFjFJJZFJLNLwrL
nLgDSHgwRgGnHjjNfTRhjPVpWV
BstQsvhQZQQbMvCvMPVNWpPcTjfmPmmW
brtCrtvtzrhdSDJDwh
dTQTwgmZQbDzzMQCCl
WLLtntFnfnRHbttnSRRzSMVGDDMGzVlV
JsPhFtfbLWnsLPLqgdJcjmcwTwjcdw
wMwMbMRRBBMLPBlhLRQlhPcWzgJNvJtzWNtJptpgjJgpBj
TnmGGmVnFFNSZsnZqFsWzWjrTJzvzWvWgWtTWz
qnHGnVSsqZCddnGCGCSNdDbLQPcLLQlDhPRMhb
NGsBTBlqsvfQBQqsTLTFltRMmRwmmHmFtPSRhM
gjZWJWCZdDpjggDdgnpWdZZJtFwFRFFRMwbbmRPtShnwRbtt
zZpSDDgpzcDddjVWggJsQGrfQvrQcTGTGrTrqr
hpJchhFWMpRDWHWcDGnCGrnGnwPTwpQnCt
bmgddgmlmjjbfddgmmmNvGQLrtfTwrTtLtGTLQVQQP
qqbmdZgzZbvgPDccHcZPhWWH
VVrdQZZrZSZFgQTTTzggrVZVMlfBBfvcMBCBslMhBvsMBSff
bQwnHwbNpwcsCwjMBw
pHqqPnJHqpPNJFzqTzQWWDQQZq
HgwTDfgBwBgcRHqRRjHqHTzQQClSzvlzPVSQLvbbPC
MnhtNZNnJpWpGhMQbCCPVSPLNmSPQQ
rrhJMFJJZFJpHcjRLFRfHjgj
vGvGMBlttBltvjdgbPsrsDWdjPPP
HnJQHVqNmQHmZsDZPPrDWpgFps
JSqJQVVDqqVfJNfRffGSGMBwGTCCCTlBMSBl
PsFZPfGbDNbtQmCCmCBBbmmL
dcRdhSrCqjThTRcTpLzHQzTmpmlgBz
hhhcqCvwhhVhfPNvsMstZtsZ
VvGwBBwvZtGgfZCqShnFFjSstCMC
NlTRdvpDdTRNzdTHHnMssCnCnCqjSz
LvWvPcWLpGwBwVVgVc
bVVmSrLmLSJzTZMSFTBdMj
QnvqRGGDvWpQWGDpvsRZLBzTRjBTtjRTPtBF
QWGvDpqcvpGWQpGngqGQGwpLhJVNJcrbfrVbfbhHrmlVJHVV
NGRGPZWZpblGcJtfssSSsbffCs
gwRhjvrgjmwgnzvJJJtVCtHJqs
rrmLrhwFFmmTMgFRjNZWNpZlZLppQNcDWP
qsHZsHZrTBtZrHBNFCJGWrMcpcddWGJWLG
mRDDzbPVDVlVDgbgRRvmwCcWdGvJwGddpvLm
PnfDbPbVzDbVfjnnlbzhVFsspBSfFsssHQNTBpFqNQ
gCmtbDqPVVVqggCGqTJjHMpMQfgMpMHQQpcM
zNZnsSLzZzrlRhTTJMHppjfHSpvp
nhdrBsLlRRrdTlsTVmCmGqDVFdtDPGwV
FnqNfdGfgzmPLGmj
blvVvbsRwgnzjCPcbT
RWWvtvphnZQZwMBNdHfNDBZZdq
DMRhDhdvnjhnPnvPMfdZSGTccGJFjGFFpFpFTbTpTW
NVgVmtzVlLBmgztsBNmtgCmqFpJJFGGpGbrcGGsrcpbWPr
zwBztLBzllQPDZvfQZfRfHSR
mFCgPzmqgtPPqMmFWzbMttcRGvRclvHhWGGcZvclRfHh
psSNnhnLGnwZHZGv
hBpNLTNLBhsPmbCgBtPDbM
JsbLLWLJRfQFnccmQhtvvPCP
dwgrVwGpgVhCrrhPDHtC
gpGSjpVdVpVppjjVZBwdCbFRWLzLMSRMbNzfzbWR
DmMQMJmnmGwzGwwG
ZcLcgLgcRsZSctHFWLGfjjBwvbvBsvjpfhGb
GgFPqFtLRHLFSHLRRFRHHtMnJVNCQCrJCJCnMJDdnqDV
tqdqFqdsRdVdtHMNdRZHTZLrHJgrlZQPJLgr
GGwVcpGznmhbWhwcVVgzTrDrDDLZlTLLZQrJ
nhbnbfjcnfMfFNVtBq
QHmPNZvfCLsSwJSm
pDhjpVDFcRBpFFjjMnRcVhpFCzbzsZbSSCtwtLMSLZLLtLbs
FRjrnRchnfHPrrZlHl
bjjMbdChgRDZthpQpRQnwRTprRwS
mGzJsGsHzHGPvvvqvzGzSnglSJrrwQgnlQQSrlQl
qvzHqHLHmHgPsNBdCdZtVBtVVMBFbh
CctrCwrdpTwcpVrdpTpcrcnSJQttvQPHJQNQnQNjvvHQ
zsqRlslRLqfgRmWsRgRzqzQnHjSBSQWJHPhHnSvHnJJJ
GRgllbgfRgbzfRmwwcGdFMcTVPrFCF`

const groupByRucksack = input.split((/\n/));

const rucksacksByCompartment = groupByRucksack.map(rucksack => {
  const firstCompartment = rucksack.substring(0,(rucksack.length)/2);
  const secondCompartment = rucksack.substring((rucksack.length)/2,rucksack.length);
  return [firstCompartment, secondCompartment]
});

// "a".charCodeAt() == 97
// "a".charCodeAt() - 96 == 1

// "A".charCodeAt() = 65
//  "A".charCodeAt() - 38 == 27

const letters = []
rucksacksByCompartment.forEach((rucksack, index) => {
  for (let i = 0; i < rucksack[0].length; i++) {
    if (rucksack[1].includes(rucksack[0][i]) && !letters.includes(index)){
      letters.push(rucksack[0][i]);
      letters.push(index);
    }
  }
})

const onlyLetters = letters.filter(value => typeof value == 'string');

let priorityPoints = 0;
onlyLetters.forEach((letter, index) => {
  if (letter.toUpperCase() === letter) {
    priorityPoints += (letter.charCodeAt() - 38);
  } else {
    // lowercase
    priorityPoints += (letter.charCodeAt() - 96);
  }
})
// console.log(priorityPoints)


let groupByN = (n, data) => {
  let result = [];
  for (let i = 0; i < data.length; i += n) result.push(data.slice(i, i + n));
  return result;
};

const elfGroups = groupByN(3, groupByRucksack);


const elfGroupLetters = []
elfGroups.forEach((rucksacks, index) => {
  const commonLettersFirstTwo = []
  for (let i = 0; i < rucksacks[0].length; i++) {
    if (rucksacks[1].includes(rucksacks[0][i])){
      commonLettersFirstTwo.push(rucksacks[0][i]);
    }
  }

  for (let i = 0; i < rucksacks[2].length; i++) {
    if (commonLettersFirstTwo.includes(rucksacks[2][i]) && !elfGroupLetters.includes(index)){
      elfGroupLetters.push(rucksacks[2][i]);
      elfGroupLetters.push(index);
    }
  }
})
const onlyLettersForElfGroups = elfGroupLetters.filter(value => typeof value == 'string');

console.log(onlyLettersForElfGroups.length)
let priorityPointsElfGroup = 0;
onlyLettersForElfGroups.forEach((letter, index) => {
  if (letter.toUpperCase() === letter) {
    priorityPointsElfGroup += (letter.charCodeAt() - 38);
  } else {
    // lowercase
    priorityPointsElfGroup += (letter.charCodeAt() - 96);
  }
})
console.log(priorityPointsElfGroup)
